Repository codestates-seb/seb40_pre_032, pull requests merged in 2022-11, with the labels that each got.

#77 [#53]:Feature/login 기능구현 완료
  public/index.html
  src/components/EditUserProfile.js
  src/components/Mainpage/MainPage.js
  src/routes/callback.js
  src/routes/login.js
  src/routes/logout.js
  src/routes/myPage.js
Labels: feature, frontend

#80 Feature/detailaccesstoken
  .gitignore
  package.json
  public/index.html
  src/App.js
  src/components/Editor.js
  src/components/Mainpage/MainPage.js
  src/components/QuestionDetail/AnswerUserInfo.js
  src/components/QuestionDetail/AnswerVotebar.js
  src/components/QuestionDetail/QuestionHeader.js
  src/components/QuestionDetail/QuestionUserInfo.js
  src/components/QuestionDetail/QuestionVotebar.js
  src/routes/AnswerEdit.js
  src/routes/QuestionDetail.js
  src/routes/QuestionEdit.js
  src/routes/login.js
  src/routes/logout.js
  src/routes/myPage.js
  src/setupProxy.js
  src/utils/hooks/useAnswer.js
  src/utils/hooks/useQuestion.js
Labels: frontend

#81 Style/qlist
  public/image/stack.png
  src/App.js
  src/components/Dummydata.js
  src/components/LoginHeader.js
  src/components/Logo.js
  src/components/Mainpage/AllQuestions.js
  src/components/Qlist.js
  src/utils/hooks/useUserActions.js
Labels: fix, frontend

#82 Feature/detailaccesstoken
  src/App.js
  src/_state/auth.js
  src/_state/userAuth.js
  src/components/AnswerEdit/AnswerEditor.js
  src/components/Editor.js
  src/components/LoginHeader.js
  src/components/Mainpage/AllQuestions.js
  src/components/Mainpage/MainPage.js
  src/components/Mainpage/QuestionHeading.js
  src/components/Qlist.js
  src/components/QuestionDetail/AnswerEditor.js
  src/components/QuestionDetail/AnswerUserInfo.js
  src/components/QuestionDetail/AnswerVotebar.js
  src/components/QuestionDetail/QuestionUserInfo.js
  src/components/QuestionDetail/QuestionVotebar.js
  src/components/QuestionEdit/QuestionEditor.js
  src/components/TagInput.js
  src/routes/AnswerEdit.js
  src/routes/QuestionDetail.js
  src/routes/QuestionEdit.js
  src/routes/login.js
  src/routes/logout.js
  src/routes/myPage.js
  src/routes/signUp.js
  src/setupProxy.js
  src/utils/hooks/useAnswer.js
  src/utils/hooks/useQuestion.js
  src/utils/hooks/useUserActions.js
Labels: frontend
